server.servlet.context-path=/inventory-processing
server.port=8082

# Enable the H2 console for web-based access (optional, for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configure the H2 database URL (in-memory mode example)
spring.datasource.url=jdbc:h2:mem:inventory
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.defer-datasource-initialization=true